### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by oooolga** [oooolga/IFT6390_Project#1]
### Implementation
- [x] Implement MLP models: @oooolga 

- [x] Impement Regression models: @zbouchlih @youngleec @Kangzf1996 

### Execution

- [x] Train CNN models using EMNIST, FMNIST and CIFAR : @oooolga 

- [x] Train NN models using EMNIST, FMNIST and CIFAR: @oooolga 

- [x] Train linear regression models using EMNIST, FMNIST and CIFAR: @zbouchlih @youngleec @Kangzf1996 

- [x] Train polynomial regression models using EMNIST, FMNIST and CIFAR: @zbouchlih @youngleec @Kangzf1996 

### Report

- [x] Abstract

- [x] Introduction  @Kangzf1996 

- [x] Approach 1: Regression model  @zbouchlih @Kangzf1996 

- [x] Approach 2: NN @oooolga 

- [x] Approach 3: CNN @oooolga 

- [x] Experiment and results for regression model @zbouchlih  @Kangzf1996  

- [x] Experiment and results for NN @oooolga 

- [x] Experiment and results for CNN @oooolga 

- [x] Discussion: @oooolga 

- [x] Conclusion and future work

**Comment by oooolga** [comment]
@zbouchlih @youngleec @Kangzf1996  Can you guys assign yourselves tasks for the writing part? I already assigned myself 5 parts.
